hellomake:
	g++ -fopenmp -O3 -march=native MMult1.cpp -o MMult1
	g++ -g val_test01_solved.cpp -o val_test01_solved
	g++ -g val_test02_solved.cpp -o val_test02_solved
	g++ -fopenmp -O3 -march=native omp_solved2.c -o omp_solved2
	g++ -fopenmp -O3 -march=native omp_solved3.c -o omp_solved3
	g++ -fopenmp -O3 -march=native omp_solved4.c -o omp_solved4
	g++ -fopenmp -O3 -march=native omp_solved5.c -o omp_solved5
	g++ -fopenmp -O3 -march=native omp_solved6.c -o omp_solved6
	g++ -fopenmp -O3 -march=native jacobi2d-omp.cpp -o jacobi2d-omp
	g++ -fopenmp -O3 -march=native gs2d-omp.cpp -o gs2d-omp