hellomake:
	g++ -fopenmp -O3 -march=native MMult1.cpp -o MMult1
	g++ -g val_test01_solved.cpp -o val_test01_solved
	g++ -g val_test02_solved.cpp -o val_test02_solved
	g++ -fopenmp -O3 -march=native omp_bug2.c -o omp_bug2
	g++ -fopenmp -O3 -march=native omp_bug3.c -o omp_bug3
	g++ -fopenmp -O3 -march=native omp_bug4.c -o omp_bug4
	g++ -fopenmp -O3 -march=native omp_bug5.c -o omp_bug5
	g++ -fopenmp -O3 -march=native omp_bug6.c -o omp_bug6